server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: auth_service
            uri: lb://auth-service
            predicates:
              - Path=/auth/**
          - id: employee_service
            uri: lb://employee-service
            predicates:
              - Path=/employees/**
          - id: config-server
            uri: lb://config-server
            predicates:
              - Path=/config/**
          - id: discovery-service
            uri: lb://DISCOVERY-SERVICE
            predicates:
              - Path=/discovery/**

  security:
    jwt:
      secret: your_secret_key