server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  main:
    allow-circular-references: true

  cloud:
    gateway:
      mvc:
        discovery:
          locator:
            enabled: true
            lowerCaseServiceId: true
        routes:
          - id: auth_service
            uri: lb://AUTH-SERVICE
            predicates:
              - Path=/api/auth/**
            filters:
              - StripPrefix=2
          - id: employee_service
            uri: lb://EMPLOYEE-SERVICE
            predicates:
              - Path=/api/employees/**
            filters:
              - StripPrefix=2
          - id: config-server
            uri: lb://CONFIG-SERVER
            predicates:
              - Path=/config/**
            filters:
              - StripPrefix=1
          - id: discovery-service
            uri: lb://DISCOVERY-SERVICE
            predicates:
              - Path=/discovery/**
            filters:
              - StripPrefix=1

  security:
    jwt:
      secret: your_secret_key