server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: employee_service
          uri: http://localhost:8082
          predicates:
            - Path=/employees/**
        - id: config-server
          uri: http://localhost:8083
          predicates:
            - Path=/config/**
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/discovery/**

  security:
    jwt:
      secret: your_secret_key