server:
  port: 8083

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/notchuks/spring-cloud-config-server.git

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka